# Project Information
site_name: NJUCS Wiki
site_description: NJUCS Wiki 是 NJU 计算机科学与技术专业的站点
site_author: NJU
site_url: https://shintou-shita.github.io/njucs-wiki/

repo_name: 'Shintou-Shita/njucs-wiki'
repo_url: 'https://github.com/Shintou-Shita/njucs-wiki'
edit_uri: 'edit/main/docs'

theme:
  name: material
  language: 'zh'
  custom_dir: overrides

# Contents
nav:
  - 简介: index.md
  - 基本技能: skills.md
  - 课程:
    - 第一学期:
      - 微积分1: Course/Calculus I.md
    - 第二学期:
      - 离散数学1: Course/Discrete Mathematics I.md
  - 友链: links.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
